// 单词数据
export const book_word = {
    word: [
        // 人教版三年级上
        {
            "unit_name": "rj_3_u_1",
            "word": ["name", "nice", "ear", "hand", "eye", "mouth", "arm", "can", "share", "smile", "listen", "help", "say", "and", "goodbye", "toy", "friend", "good"]
        },
        {
            "unit_name": "rj_3_u_2",
            "word": [
                "mum", "dad", "grandma", "grandpa", "grandfather", "grandmother",
                "mother", "father", "me", "sister", "family", "have", "big",
                "cousin", "brother", "baby", "uncle", "aunt", "some", "small"
            ]
        },
        {
            "unit_name": "rj_3_u_3",
            "word": [
                "like", "dog", "pet", "cat", "fish", "bird", "rabbit", "go", "zoo",
                "fox", "Miss", "panda", "red", "cute", "monkey", "tiger", "elephant",
                "lion", "animal", "giraffe", "tall", "fast"
            ]
        },
        {
            "unit_name": "rj_3_u_4",
            "word": [
                "apple", "banana", "farm", "air", "orange", "grape", "school",
                "garden", "need", "water", "flower", "grass", "plant", "new",
                "tree", "sun", "give", "us", "them"
            ]
        },
        {
            "unit_name": "rj_3_u_5",
            "word": [
                "colour", "orange", "green", "red", "blue", "make", "purple",
                "brown", "bear", "yellow", "duck", "sea", "pink", "draw",
                "white", "black"
            ]
        },
        {
            "unit_name": "rj_3_u_6",
            "word": [
                "old", "five", "year", "one", "two", "three", "four",
                "ten", "six", "seven", "eight", "nine", "o'clock",
                "cut", "eat", "cake"
            ]
        },
        // 人教版五年级上
        {
            "unit_name": "rj_5_u_1",
            "word": [
                "old",
                "young",
                "funny",
                "kind",
                "strict",
                "polite",
                "hard-working",
                "helpful",
                "clever",
                "shy",
                "know",
                "our",
                "Ms",
                "will",
                "sometimes",
                "robot",
                "him",
                "speak"
            ]
        },
        {
            "unit_name": "rj_5_u_2",
            "word": [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday",
                "weekend",
                "wash",
                "watch",
                "do",
                "read",
                "play",
                "cooking",
                "often",
                "park",
                "tired",
                "sport",
                "should",
                "every",
                "day",
                "schedule",
                "Dear",
                "onion"
            ]
        },
        {
            "unit_name": "rj_5_u_3",
            "word": [
                "sandwich",
                "salad",
                "hamburger",
                "ice cream",
                "tea",
                "fresh",
                "healthy",
                "delicious",
                "hot",
                "sweet",
                "drink",
                "thirsty",
                "favourite",
                "food",
                "Dear",
                "onion"
            ]
        },
        {
            "unit_name": "rj_5_u_4",
            "word": [
                "sing",
                "song",
                "sing English songs",
                "play the pipa",
                "kung fu",
                "do kung fu",
                "dance",
                "draw",
                "cartoon",
                "draw cartoons",
                "cook",
                "swim",
                "play basketball",
                "ping-pong",
                "play ping-pong",
                "speak English",
                "we'll",
                "party",
                "next",
                "wonderful",
                "learn",
                "any",
                "problem",
                "no problem",
                "want",
                "send",
                "email",
                "at"
            ]
        },
        {
            "unit_name": "rj_5_u_5",
            "word": [
                "clock",
                "plant",
                "bottle",
                "water bottle",
                "bike",
                "photo",
                "front",
                "in front of",
                "between",
                "above",
                "beside",
                "behind",
                "there",
                "grandparent",
                "their",
                "house",
                "lot",
                "lots of",
                "flower",
                "move",
                "dirty",
                "everywhere",
                "mouse",
                "live",
                "nature"
            ]
        },
        {
            "unit_name": "rj_5_u_6",
            "word": [
                "forest",
                "river",
                "lake",
                "mountain",
                "hill",
                "tree",
                "bridge",
                "building",
                "village",
                "house",
                "boating",
                "go boating",
                "aren't",
                "rabbit",
                "high"
            ]
        },
        // 人教版五年级下
        {
            "unit_name": "rj_5_d_1",
            "word": [
                "eat breakfast",
                "have ... class",
                "play sports",
                "exercise",
                "do morning exercises",
                "eat dinner",
                "clean my room",
                "go for a walk",
                "go shopping",
                "take",
                "dancing",
                "take a dancing class",
                "when",
                "after",
                "start",
                "usually",
                "Spain",
                "late",
                "a.m.",
                "p.m.",
                "why",
                "shop",
                "work",
                "last",
                "sound",
                "also",
                "busy",
                "need",
                "play",
                "letter",
                "live",
                "island",
                "always",
                "cave",
                "go swimming",
                "win"
            ]
        },
        {
            "unit_name": "rj_5_d_2",
            "word": [
                "spring",
                "summer",
                "autumn",
                "winter",
                "season",
                "picnic",
                "go on a picnic",
                "pick",
                "pick apples",
                "snowman",
                "make a snowman",
                "go swimming",
                "which",
                "best",
                "snow",
                "good job",
                "because",
                "vacation",
                "all",
                "pink",
                "lovely",
                "leaf",
                "fall",
                "paint"
            ]
        },
        {
            "unit_name": "rj_5_d_3",
            "word": [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
                "few",
                "a few",
                "thing",
                "meet",
                "sports meet",
                "trip",
                "year",
                "plant",
                "contest",
                "labour",
                "Labour Day",
                "the Great Wall",
                "national",
                "National Day",
                "American",
                "Thanksgiving",
                "Christmas",
                "game",
                "riddle",
                "act",
                "act out",
                "RSVP",
                "by"
            ]
        },
        {
            "unit_name": "rj_5_d_4",
            "word": [
                "first (1st)",
                "second (2nd)",
                "third (3rd)",
                "fourth (4th)",
                "fifth (5th)",
                "twelfth (12th)",
                "twentieth (20th)",
                "twenty-first (21st)",
                "twenty-third (23rd)",
                "thirtieth (30th)",
                "other",
                "special",
                "show",
                "festival",
                "kitten",
                "diary",
                "still",
                "noise",
                "fur",
                "open",
                "walk"
            ]
        },
        {
            "unit_name": "rj_5_d_5",
            "word": [
                "mine",
                "yours",
                "his",
                "hers",
                "theirs",
                "ours",
                "climbing",
                "eating",
                "playing",
                "jumping",
                "drinking",
                "sleeping",
                "each",
                "each other",
                "excited",
                "like"
            ]
        },
        {
            "unit_name": "rj_5_d_6",
            "word": [
                "doing morning exercises",
                "having ... class",
                "eating lunch",
                "reading a book",
                "listening to music",
                "keep",
                "keep to the right",
                "keep your desk clean",
                "talk quietly",
                "turn",
                "take turns",
                "bamboo",
                "its",
                "show",
                "anything",
                "else",
                "exhibition",
                "say",
                "have a look",
                "sushi",
                "teach",
                "sure",
                "Canadian",
                "Spanish"
            ]
        },
        // 人教版六年级上
        {
            "unit_name": "rj_6_u_1",
            "word": [
                "science",
                "museum",
                "post office",
                "bookstore",
                "cinema",
                "hospital",
                "crossing",
                "turn",
                "left",
                "straight",
                "right",
                "ask",
                "sir",
                "interesting",
                "Italian",
                "restaurant",
                "pizza",
                "street",
                "get",
                "BDS",
                "gave",
                "feature",
                "follow",
                "far",
                "tell"
            ],
        },
        {
            "unit_name": "rj_6_u_2",
            "word": [
                "on foot",
                "by",
                "bus",
                "plane",
                "taxi",
                "ship",
                "subway",
                "train",
                "slow",
                "down",
                "slow down",
                "stop",
                "Mrs",
                "early",
                "helmet",
                "must",
                "wear",
                "attention",
                "pay attention to",
                "traffic",
                "traffic lights",
                "Munich",
                "Germany",
                "Alaska",
                "sled",
                "fast",
                "ferry",
                "Papa Westray",
                "Scotland"
            ]
        },
        {
            "unit_name": "rj_6_u_3",
            "word": [
                "visit",
                "film",
                "see a film",
                "trip",
                "take a trip",
                "supermarket",
                "evening",
                "tonight",
                "tomorrow",
                "next week",
                "dictionary",
                "comic",
                "comic book",
                "word",
                "word book",
                "postcard",
                "lesson",
                "space",
                "travel",
                "half",
                "price",
                "Mid-Autumn Festival",
                "together",
                "get together",
                "mooncake",
                "poem",
                "moon"
            ]
        },
        {
            "unit_name": "rj_6_u_4",
            "word": [
                "studies",
                "puzzle",
                "hiking",
                "pen pal",
                "hobby",
                "jasmine",
                "idea",
                "Canberra",
                "amazing",
                "shall",
                "goal",
                "join",
                "club",
                "share"
            ]
        },
        {
            "unit_name": "rj_6_u_5",
            "word": [
                "factory",
                "worker",
                "postman",
                "businessman",
                "police officer",
                "fisherman",
                "scientist",
                "pilot",
                "coach",
                "country",
                "head teacher",
                "sea",
                "stay",
                "university",
                "gym",
                "if",
                "reporter",
                "use",
                "type",
                "quickly",
                "secretary"
            ]
        },
        {
            "unit_name": "rj_6_u_6",
            "word": [
                "angry",
                "afraid",
                "sad",
                "worried",
                "happy",
                "see a doctor",
                "wear",
                "more",
                "deep",
                "breath",
                "take a deep breath",
                "count",
                "count to ten",
                "chase",
                "mice",
                "bad",
                "hurt",
                "ill",
                "wrong",
                "should",
                "feel",
                "well",
                "sit",
                "grass",
                "hear",
                "ant",
                "worry",
                "stuck",
                "mud",
                "pull",
                "everyone"
            ]
        },
        // 人教版六年级下
        {
            "unit_name": "rj_6_d_1",
            "word": [
                "younger",
                "older",
                "taller",
                "shorter",
                "longer",
                "thinner",
                "heavier",
                "bigger",
                "smaller",
                "stronger",
                "dinosaur",
                "hall",
                "metre",
                "than",
                "both",
                "kilogram",
                "countryside",
                "lower",
                "shadow",
                "smarter",
                "become"
            ]
        },
        {
            "unit_name": "rj_6_d_2",
            "word": [
                "cleaned",
                "stayed",
                "washed",
                "watched",
                "had",
                "slept",
                "read",
                "saw",
                "last",
                "yesterday",
                "before",
                "drank",
                "show",
                "magazine",
                "better",
                "faster",
                "hotel",
                "fixed",
                "broken",
                "lamp",
                "loud",
                "enjoy",
                "stay"
            ]
        },
        {
            "unit_name": "rj_6_d_3",
            "word": [
                "went",
                "camp",
                "went camping",
                "fish",
                "went fishing",
                "rode",
                "hurt",
                "ate",
                "took",
                "took pictures",
                "bought",
                "gift",
                "fell",
                "off",
                "Labour Day",
                "mule",
                "Turpan",
                "could",
                "till",
                "beach",
                "basket",
                "part",
                "licked",
                "laughed"
            ]
        },
        {
            "unit_name": "rj_6_d_4",
            "word": [
                "dining hall",
                "grass",
                "gym",
                "ago",
                "cycling",
                "go cycling",
                "ice-skate",
                "badminton",
                "star",
                "easy",
                "look up",
                "Internet",
                "different",
                "active",
                "race",
                "nothing",
                "thought",
                "felt",
                "cheetah",
                "trip",
                "woke",
                "dream"
            ]
        },
        // 外研版三年级上
        {
            "unit_name": "wy_3_u_welcome",
            "word": [
                "hi",
                "I",
                "be",
                "what",
                "your",
                "name",
                "hello",
                "my",
                "goodbye",
                "have",
                "a",
                "nice",
                "day",
                "good",
                "morning",
                "Ms",
                "stand",
                "stand up",
                "sit",
                "sit down",
                "open",
                "book",
                "close",
                "point",
                "say",
                "read",
                "listen",
                "write"
            ]
        },
        {
            "unit_name": "wy_3_u_1",
            "word": [
                "let's",
                "friend",
                "to",
                "meet",
                "you",
                "play",
                "happy",
                "new",
                "do",
                "they",
                "welcome",
                "everyone",
                "nine",
                "she",
                "too",
                "we",
                "from",
                "the",
                "twin",
                "he",
                "come",
                "and",
                "oh",
                "no",
                "help",
                "here",
                "here you are",
                "thank",
                "together",
                "OK",
                "great",
                "song",
                "dear",
                "sing",
                "now",
                "know",
                "our",
                "everybody",
                "with",
                "me"
            ]
        },
        {
            "unit_name": "wy_3_u_2",
            "word": [
                "school",
                "thing",
                "pack",
                "pen",
                "pencil",
                "pencil case",
                "bag",
                "for",
                "ruler",
                "eraser",
                "this",
                "in",
                "schoolbag",
                "it",
                "not",
                "that",
                "yes",
                "guess",
                "find",
                "lost and found",
                "bye",
                "kid",
                "take care of sb / sth",
                "there",
                "please",
                "back",
                "come back",
                "look",
                "look at sb / sth"
            ]
        },
        {
            "unit_name": "wy_3_u_3",
            "word": [
                "colourful",
                "world",
                "hooray",
                "umbrella",
                "clothes",
                "red",
                "pink",
                "green",
                "yellow",
                "orange",
                "blue",
                "purple",
                "rainbow",
                "want",
                "balloon",
                "colour",
                "can",
                "see",
                "right",
                "first",
                "magical",
                "fun",
                "black",
                "so",
                "many",
                "picture",
                "today",
                "paint"
            ]
        },
        {
            "unit_name": "wy_3_u_4",
            "word": [
                "number",
                "count",
                "how",
                "bird",
                "one",
                "two",
                "three",
                "four",
                "five",
                "six",
                "seven",
                "eight",
                "ten",
                "eleven",
                "twelve",
                "rope",
                "who",
                "make",
                "Chinese knot",
                "beautiful",
                "only",
                "amazing",
                "show",
                "baby",
                "cheep",
                "egg",
                "hungry",
                "around",
                "all",
                "all around",
                "big",
                "little",
                "everywhere"
            ]
        },
        {
            "unit_name": "wy_3_u_5",
            "word": [
                "family",
                "dad",
                "mum",
                "brother",
                "sister",
                "grandpa",
                "grandma",
                "but",
                "people",
                "story",
                "cap",
                "worry",
                "on",
                "come on",
                "photo",
                "love",
                "daddy",
                "mummy",
                "where",
                "dog",
                "box"
            ]
        },
        {
            "unit_name": "wy_3_u_6",
            "word": [
                "sweet",
                "home",
                "game",
                "room",
                "living room",
                "bedroom",
                "bathroom",
                "kitchen",
                "dining room",
                "door",
                "chair",
                "think",
                "under",
                "bed",
                "toy",
                "miaow",
                "table",
                "cat",
                "ball",
                "their",
                "apple",
                "share",
                "put",
                "cooking",
                "sun",
                "like",
                "run",
                "lucky"
            ]
        },
        // 外研版四年级上
        {
            "unit_name": "wy_4_u_1",
            "word": [
                "straight",
                "go straight on",
                "left",
                "right",
                "lost",
                "live",
                "No.",
                "street",
                "excuse me",
                "turn left",
                "turn right",
                "next to",
                "supermarket",
                "beside",
                "cinema",
                "so much",
                "You're welcome!",
                "station",
                "train",
                "hill",
                "near",
                "house"
            ]
        },
        {
            "unit_name": "wy_4_u_2",
            "word": [
                "list",
                "er",
                "need",
                "first",
                "can",
                "lost",
                "how much",
                "cheese",
                "any",
                "use",
                "over there",
                "bottle",
                "half",
                "kilo",
                "a lot of"
            ]
        },
        {
            "unit_name": "wy_4_u_3",
            "word": [
                "weekend",
                "place",
                "British",
                "museum",
                "how",
                "best",
                "took",
                "trip",
                "along",
                "river",
                "hour",
                "twenty",
                "minute",
                "of",
                "wall",
                "arrive",
                "for",
                "mountain",
                "with",
                "plant"
            ]
        },
        {
            "unit_name": "wy_4_u_4",
            "word": [
                "want",
                "some",
                "juice",
                "ice",
                "also",
                "food",
                "fast food",
                "make",
                "tomato",
                "egg",
                "potato",
                "How much...?",
                "flower",
                "dumpling",
                "help",
                "buy"
            ]
        },
        {
            "unit_name": "wy_4_u_5",
            "word": [
                "run",
                "fast",
                "sky",
                "high",
                "winner",
                "far",
                "afraid",
                "strong",
                "star"
            ]
        },
        {
            "unit_name": "wy_4_u_6",
            "word": [
                "sweets",
                "soup",
                "sorry",
                "bread",
                "dark",
                "well",
                "turn on",
                "light",
                "the Mid-Autumn Festival",
                "moon",
                "moon cake",
                "of course"
            ]
        },
        {
            "unit_name": "wy_4_u_7",
            "word": [
                "there is",
                "horse",
                "there are",
                "have a look",
                "sheep",
                "vegetable",
                "climb",
                "face",
                "fruit",
                "chicken",
                "bear",
                "pig"
            ]
        },
        {
            "unit_name": "wy_4_u_8",
            "word": [
                "visit",
                "tomorrow",
                "plane",
                "get up",
                "o'clock",
                "from",
                "sea",
                "swimsuit",
                "sock",
                "fish",
                "hooray"
            ]
        },
        {
            "unit_name": "wy_4_u_9",
            "word": [
                "sports day",
                "win",
                "month",
                "hundred",
                "metre",
                "every",
                "day",
                "luck",
                "good luck",
                "come on",
                "high jump",
                "long jump",
                "How about...?",
                "subject"
            ]
        },
        {
            "unit_name": "wy_4_u_10",
            "word": [
                "family",
                "dinner",
                "year",
                "New Year",
                "Chinese",
                "festival",
                "the Spring Festival",
                "I see.",
                "peanut",
                "merry",
                "Christmas",
                "Merry Christmas!"
            ]
        },
        // 外研版四年级下
        {
            "unit_name": "wy_4_d_1",
            "word": [
                "nice", "clever", "naughty", "a bit", "shy", "answer",
                "call", "bad", "cool", "aunt", "uncle", "big",
                "little", "cute"
            ]
        },
        {
            "unit_name": "wy_4_d_2",
            "word": [
                "city", "ship", "beautiful", "whose", "queen",
                "close", "old", "famous"
            ]
        },
        {
            "unit_name": "wy_4_d_3",
            "word": [
                "robot", "will", "everything", "one day", "housework",
                "learn", "our", "homework", "won’t", "Tuesday",
                "Wednesday", "Thursday", "Friday", "have", "next",
                "week", "holiday"
            ]
        },
        {
            "unit_name": "wy_4_d_4",
            "word": [
                "take", "fly", "picnic", "great", "why",
                "Why not?", "because", "so", "cloudy", "weather"
            ]
        },
        {
            "unit_name": "wy_4_d_5",
            "word": [
                "was", "then", "grandparent", "were", "young",
                "old", "hair", "so", "short", "long",
                "wasn’t", "weren’t", "clean", "dirty"
            ]
        },
        {
            "unit_name": "wy_4_d_6",
            "word": [
                "yesterday", "out", "well", "thanks", "sun",
                "lesson", "village"
            ]
        },
        {
            "unit_name": "wy_4_d_7",
            "word": [
                "had", "phone", "cook", "really", "wash",
                "What about?", "did", "didn’t", "computer",
                "love", "him", "Mrs", "Miss"
            ]
        },
        {
            "unit_name": "wy_4_d_8",
            "word": [
                "beautifully", "saw", "game", "last", "fun",
                "went", "there", "ate", "drank", "drink",
                "time", "have a good time", "busy", "took",
                "tell", "great", "delicious", "made", "poster"
            ]
        },
        {
            "unit_name": "wy_4_d_9",
            "word": [
                "welcome", "postcard", "cousin", "dear", "on holiday",
                "travel", "came", "pop", "concert", "earth"
            ]
        },
        {
            "unit_name": "wy_4_d_10",
            "word": [
                "fall", "fall off", "fell", "fall down", "found",
                "town", "happen", "ride", "then", "thirsty",
                "water", "bought", "watermelon", "carried", "bump",
                "hospital", "had", "chocolate", "stomach ache",
                "cold", "headache", "fever"
            ]
        },
    ]
}